"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import categorySheet from "./web-category-sheet.png?url";

type Product = { id: number; name: string; family?: string; category?: string; subfamily?: string; brand?: string; format?: string; sku?: string; unit_price?: number; deleted?: number; product_status?: string };
type RegistrationKind = "cliente" | "proveedor";

const categoryCards = [
  ["01", "Cervezas", "Barril, botellín y referencias para llenar tu cámara."],
  ["02", "Vinos y vermuts", "Bodegas, denominaciones y formatos para cada servicio."],
  ["03", "Refrescos", "Las marcas y sabores que tus clientes ya conocen."],
  ["04", "Aguas y mixers", "La base de una carta cuidada y una mesa completa."],
];
const zones = [
  ["01", "Palencia capital y alfoz", "Servicio continuo en Palencia, Villamuriel y Grijota."],
  ["02", "Comarca del Cerrato", "Rutas coordinadas para Dueñas, Venta de Baños y pueblos cercanos."],
  ["03", "Tierra de Campos y norte", "Planificamos la entrega para que el género llegue cuando lo necesitas."],
];
const productCategory = (product: Product) => String(product.family || product.category || product.subfamily || "Selección horeca").trim();
const offerLabels = ["Oferta de alta", "Descuento por volumen", "Condición especial horeca", "Promoción de temporada"];

export default function WebPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Todos");
  const [menuOpen, setMenuOpen] = useState(false);
  const [registrationKind, setRegistrationKind] = useState<RegistrationKind | null>(null);
  const [registrationSaving, setRegistrationSaving] = useState(false);
  const [registrationMessage, setRegistrationMessage] = useState("");
  const [registration, setRegistration] = useState({ company_name: "", tax_id: "", contact_name: "", email: "", phone: "", address: "", city: "", message: "" });

  useEffect(() => {
    let mounted = true;
    fetch("/api/products?limit=300", { headers: { "X-Audit-Query": "true" } }).then((response) => response.json()).then((data) => { if (mounted) setProducts(Array.isArray(data) ? data.filter((item) => Number(item.deleted || 0) === 0 && item.product_status !== "Baja") : []); }).catch(() => { if (mounted) setProducts([]); }).finally(() => { if (mounted) setLoading(false); });
    return () => { mounted = false; };
  }, []);
  const categories = useMemo(() => Array.from(new Set(products.map(productCategory))).filter(Boolean).slice(0, 14), [products]);
  const filteredProducts = useMemo(() => products.filter((product) => { const text = `${product.name || ""} ${product.sku || ""} ${product.brand || ""} ${product.family || ""} ${product.category || ""} ${product.format || ""}`.toLowerCase(); return (!query.trim() || text.includes(query.trim().toLowerCase())) && (category === "Todos" || productCategory(product) === category); }), [products, query, category]);
  function openRegistration(kind: RegistrationKind) { setRegistrationKind(kind); setRegistrationMessage(""); setRegistration({ company_name: "", tax_id: "", contact_name: "", email: "", phone: "", address: "", city: "", message: "" }); }
  async function submitRegistration(event: FormEvent) { event.preventDefault(); if (!registrationKind) return; setRegistrationSaving(true); setRegistrationMessage(""); try { const response = await fetch("/api/web_registrations", { method: "POST", headers: { "Content-Type": "application/json", "X-Actor": "Portal web" }, body: JSON.stringify({ ...registration, kind: registrationKind }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "No se ha podido enviar el formulario."); setRegistrationMessage("Recibido. Nuestro equipo revisará los datos y se pondrá en contacto contigo."); } catch (error) { setRegistrationMessage(error instanceof Error ? error.message : "No se ha podido enviar el formulario."); } finally { setRegistrationSaving(false); } }
  return <main className="public-web">
    <header className="public-web-header"><a className="public-web-brand" href="#inicio" aria-label="Exclusivas Inteligentes, inicio"><span>E</span><div><b>Exclusivas</b><small>Inteligentes</small></div></a><button className="public-web-menu-toggle" type="button" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)}><i /><i /><i /></button><nav className={menuOpen ? "is-open" : ""} aria-label="Navegación principal"><a href="#catalogo" onClick={() => setMenuOpen(false)}>Ofertas</a><a href="#servicio" onClick={() => setMenuOpen(false)}>Servicio</a><a href="#altas" onClick={() => setMenuOpen(false)}>Regístrate</a></nav><a className="public-web-order-link" href="/portal-pedidos">Mi pedido <span>↗</span></a></header>
    <section className="public-web-hero" id="inicio"><div className="public-web-hero-copy"><p className="public-web-kicker">DISTRIBUCIÓN HORECA · PALENCIA</p><h1>Más género, mejores <em>condiciones.</em></h1><p className="public-web-hero-lead">Descubre ofertas profesionales, servicio cercano y un catálogo pensado para que tu negocio venda más.</p><div className="public-web-hero-actions"><a className="public-web-primary" href="#catalogo">Ver ofertas <span>↓</span></a><a className="public-web-text-link" href="#altas">Acceder a condiciones <span>→</span></a></div></div><div className="public-web-hero-art" aria-hidden="true"><div className="public-web-orbit orbit-one" /><div className="public-web-orbit orbit-two" /><div className="public-web-bottle bottle-dark"><i /><b>01</b></div><div className="public-web-bottle bottle-light"><i /><b>02</b></div><div className="public-web-bottle bottle-red"><i /><b>03</b></div><strong>BRINDAMOS<br />POR LO QUE<br /><span>VIENE.</span></strong></div><div className="public-web-hero-bottom"><span>Registro gratuito</span><span>Ofertas para profesionales</span><span>Rutas semanales</span></div></section>
    <section className="public-web-intro"><p className="public-web-kicker">VENTAJAS DE REGISTRARTE</p><div><h2>Todo lo que necesitas para servir <em>mejor.</em></h2><p>Seleccionamos referencias para hostelería y reservamos las mejores condiciones para quienes trabajan con nosotros.</p><div className="public-web-benefits"><span><b>01</b>Ofertas y descuentos</span><span><b>02</b>Pedidos desde cualquier dispositivo</span><span><b>03</b>Atención comercial cercana</span></div></div></section>
    <section className="public-web-category-grid" aria-label="Categorías de producto">{categoryCards.map(([number, title, text]) => <a className="public-web-category-card" href="#catalogo" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><b>↗</b></a>)}</section>
    <section className="public-web-catalog-section" id="catalogo"><div className="public-web-section-head"><div><p className="public-web-kicker">SELECCIÓN PARA TU NEGOCIO</p><h2>Ofertas para profesionales <em>como tú.</em></h2></div><span>{loading ? "Cargando ofertas…" : `${filteredProducts.length} referencias seleccionadas`}</span></div><div className="public-web-catalog-toolbar"><label><span className="sr-only">Buscar en catálogo</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busca por producto, marca o formato…" /></label><div className="public-web-category-pills"><button className={category === "Todos" ? "active" : ""} onClick={() => setCategory("Todos")}>Todos</button>{categories.slice(0, 7).map((item) => <button className={category === item ? "active" : ""} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="public-web-product-grid">{loading ? <div className="public-web-empty">Cargando referencias del catálogo…</div> : filteredProducts.slice(0, 12).map((product, index) => <article className={`public-web-product-card tone-${index % 4}`} key={product.id}><div className={`public-web-product-image crop-${index % 4}`}><img src={categorySheet} alt="" /><span>{String(index + 1).padStart(2, "0")}</span><strong>{offerLabels[index % offerLabels.length]}</strong></div><div className="public-web-product-info"><small>{productCategory(product)}{product.format ? ` · ${product.format}` : ""}</small><h3>{product.name}</h3><p>{product.brand || product.sku || "Referencia profesional"}</p><div><b>Consultar oferta</b><a href="/portal-pedidos" aria-label={`Solicitar oferta de ${product.name}`}>Solicitar condiciones <span>+</span></a></div></div></article>)}{!loading && !filteredProducts.length && <div className="public-web-empty">No encontramos esa referencia. Prueba con otra búsqueda.</div>}</div><div className="public-web-catalog-footer"><span>Las condiciones y descuentos se muestran tras el registro</span><a href="#altas">Quiero registrarme <span>→</span></a></div></section>
    <section className="public-web-service" id="servicio"><div className="public-web-service-copy"><p className="public-web-kicker">NO SOLO REPARTIMOS</p><h2>Tu ruta, nuestra <em>responsabilidad.</em></h2><p>Sabemos que la entrega no termina cuando dejamos el género. Te ayudamos a elegir referencias, planificar compras y evitar roturas de stock.</p><a className="public-web-text-link" href="#altas">Habla con nuestro equipo <span>→</span></a></div><div className="public-web-zone-list">{zones.map(([number, title, text]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><b>↗</b></article>)}</div></section>
    <section className="public-web-register" id="altas"><div><p className="public-web-kicker">EMPEZAMOS POR ESCUCHARTE</p><h2>Regístrate y descubre tus <em>condiciones.</em></h2><p>Si eres un negocio de hostelería o un proveedor que quiere colaborar, déjanos tus datos. Validaremos la solicitud en el CRM y te responderemos personalmente.</p></div><div className="public-web-register-actions"><button onClick={() => openRegistration("cliente")}>Quiero ofertas <span>→</span></button><button onClick={() => openRegistration("proveedor")}>Quiero colaborar <span>→</span></button></div></section>
    <footer className="public-web-footer"><a className="public-web-brand" href="#inicio"><span>E</span><div><b>Exclusivas</b><small>Inteligentes</small></div></a><p>Distribución profesional de bebidas · Palencia</p><div><a href="mailto:comercial@exclusivasinteligentes.es">Contactar</a><a href="/portal-pedidos">Pedidos</a></div></footer>
    {registrationKind && <div className="public-web-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !registrationSaving) setRegistrationKind(null); }}><section className="public-web-registration-modal" role="dialog" aria-modal="true" aria-labelledby="web-registration-title"><button className="public-web-modal-close" type="button" onClick={() => !registrationSaving && setRegistrationKind(null)} aria-label="Cerrar">×</button>{registrationMessage ? <div className="public-web-form-success"><span>✓</span><p className="public-web-kicker">SOLICITUD RECIBIDA</p><h2>Gracias por contactar.</h2><p>{registrationMessage}</p><button className="public-web-primary" type="button" onClick={() => setRegistrationKind(null)}>Cerrar</button></div> : <form onSubmit={submitRegistration}><p className="public-web-kicker">ALTA PROFESIONAL</p><h2 id="web-registration-title">{registrationKind === "cliente" ? "Quiero ser cliente" : "Quiero ser proveedor"}</h2><p>Estos datos quedarán pendientes de validación por nuestro equipo comercial.</p><div className="public-web-form-grid"><label>Empresa *<input required value={registration.company_name} onChange={(event) => setRegistration({ ...registration, company_name: event.target.value })} /></label><label>NIF/CIF<input value={registration.tax_id} onChange={(event) => setRegistration({ ...registration, tax_id: event.target.value })} /></label><label>Persona de contacto *<input required value={registration.contact_name} onChange={(event) => setRegistration({ ...registration, contact_name: event.target.value })} /></label><label>Email *<input required type="email" value={registration.email} onChange={(event) => setRegistration({ ...registration, email: event.target.value })} /></label><label>Teléfono<input value={registration.phone} onChange={(event) => setRegistration({ ...registration, phone: event.target.value })} /></label><label>Ciudad<input value={registration.city} onChange={(event) => setRegistration({ ...registration, city: event.target.value })} /></label><label className="wide">Dirección<input value={registration.address} onChange={(event) => setRegistration({ ...registration, address: event.target.value })} /></label><label className="wide">Cuéntanos qué necesitas<textarea rows={3} value={registration.message} onChange={(event) => setRegistration({ ...registration, message: event.target.value })} /></label></div><button className="public-web-primary public-web-form-submit" disabled={registrationSaving}>{registrationSaving ? "Enviando…" : "Enviar solicitud"}<span>→</span></button></form>}</section></div>}
  </main>;
}
